### PR TITLE
Move article to vignettes top-level + build ignore it

### PR DESCRIPTION
**Pull request by olivroy**
About your other question in https://github.com/mtennekes/cols4all/pull/36#issuecomment-2423156107

You can now just add the file to the `pkgdown/assets` directory and it will be available for download on the website.

See what I did in gt for example.

https://gt.rstudio.com/gt-latex.pdf stored in https://github.com/rstudio/gt/tree/master/pkgdown/assets

### CODE REVIEW

**Comment by olivroy** [comment]
Still not working.. Honestly, can't tell what is going on..

**Comment by mtennekes** [comment]
For me it does seem to work :-) Maybe you'll need to clean the browser cache?

**Comment by olivroy** [comment]
OH! Nice Awesome

**Comment by mtennekes** [comment]
Yes! Also the download works https://mtennekes.github.io/cols4all/paletteer.rds

Many thanks

**Pull request merged**
