### PR TITLE
Deal with kableExtra not being on CRAN

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Heads-up @mtennekes this is still not working for me and I'm not sure why, my patch has failed : (

```r
remotes::install_github("robinlovelace/cols4all", ref = "patch-1")
```

**Comment by Robinlovelace** [comment]
This works:

```r
remotes::install_github("haozhu233/kableExtra")
```

**Comment by mtennekes** [comment]
Hi @Robinlovelace I just checked, and kableExtra seems to be available on CRAN: https://cran.r-project.org/web/packages/kableExtra/index.html

Do you still have this issue?

**Comment by Robinlovelace** [comment]
Weird. Good to see it's back!

**Pull request closed without merging**
